WillingToJoin/Areas/CRM/Models/HouseholdViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WillingToJoin.Areas.CRM.Models
{
    public class HouseholdViewModel
    {
        public int ID { get; set; }
        public string ImportedID { get; set; }
        public string OwnerID { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Html)]
        [AllowHtml]
        public string Npo02FormulaMailingAddress { get; set; }
        public string Npo02HouseholdEmail { get; set; }
        public string Npo02HouseholdPhone { get; set; }
        public string Npo02MailingCity { get; set; }
        public string Npo02MailingPostalCode { get; set; }
        public string Npo02MailingState { get; set; }
        public string Npo02MailingStreet { get; set; }
        public string Npo02FormalGreeting { get; set; }
        public string Npo02InformalGreeting { get; set; }
        public string CvmReID { get; set; }
        public bool ExportedToCvm { get; set; }
        public string Note { get; set; }
        public string CvmFormalGreeting { get; set; }
        public string CvmInformalGreeting { get; set; }
        public string GroupSource { get; set; }
    }
}

WillingToJoin/Areas/CRM2/Models/HouseholdsViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WillingToJoin.Areas.CRM2.Models
{
    public class HouseholdsViewModel
    {
        public int ID { get; set; }
        public string ImportedID { get; set; }
        public string OwnerID { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Html)]
        [AllowHtml]
        public string Npo02FormulaMailingAddress { get; set; }
        public string Npo02HouseholdEmail { get; set; }
        public string Npo02HouseholdPhone { get; set; }
        public string Npo02MailingCity { get; set; }
        public string Npo02MailingPostalCode { get; set; }
        public string Npo02MailingState { get; set; }
        public string Npo02MailingStreet { get; set; }
        public string Npo02FormalGreeting { get; set; }
        public string Npo02InformalGreeting { get; set; }
        public string CvmReID { get; set; }
        public bool ExportedToCvm { get; set; }
        public string Note { get; set; }
        public string CvmFormalGreeting { get; set; }
        public string CvmInformalGreeting { get; set; }
        public int HouseholdStatusID { get; set; }
        public string GroupSource { get; set; }
    }
}

WillingToJoin/Areas/CRM/Controllers/HouseholdController.cs
using System.Collections.Generic;
using AutoMapper;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System.Linq;
using System.Web.Mvc;
using WillingToJoin.Areas.CRM.Models;
using WillingToJoin.Shared.Data;
using WillingToJoin.Shared.Domain;
using WillingToJoin.Shared.Services.Contacts;

namespace WillingToJoin.Areas.CRM.Controllers
{
    public class HouseholdController : Controller
    {
        private readonly IHouseholdService _service;
        private readonly IContactService _contactService;
        private readonly IMapper _mapper;
        public HouseholdController(IHouseholdService service, IContactService contactService, IMapper mapper)
        {
            _service = service;
            _contactService = contactService;
            _mapper = mapper;
        }

        // GET: CRM/Household
        public ActionResult Index()
        {
	        PopulateHouseholdStatus();
            return View();
        }

		public ActionResult Household()
		{
			PopulateHouseholdStatus();
			return View();
		}

		public void PopulateHouseholdStatus()
	    {
		    WTJContext context = new WTJContext();
		    var statuses = context.HouseholdStatuses.ToList();
		    List<SelectListItem> householdStatuses = statuses.Select(status => new SelectListItem
		    {
			    Value = status.HouseholdStatusID.ToString(), Text = status.Name
		    }).ToList();

		    ViewData["householdStatuses"] = householdStatuses;
		}

        public ActionResult HouseholdNote_Read([DataSourceRequest]DataSourceRequest request)
        {
            return null; //Json(GetOrders().ToDataSourceResult(request));
        }

        #region Grid Actions
        public ActionResult HierarchyBinding_Contacts(int householdID, [DataSourceRequest] DataSourceRequest request)
        {
            var entities = _contactService.GetAll();
            return Json(entities.Where<Contact>(w => w.HouseholdID == householdID)
                .ToDataSourceResult(request, s => _mapper.Map<ContactViewModel>(s)));
        }

        public ActionResult Household_Read([DataSourceRequest]DataSourceRequest request)
        {
            var entities = _service.GetAll();
            return Json(entities.ToDataSourceResult(request, s => _mapper.Map<HouseholdViewModel>(s)));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Household_Create([DataSourceRequest] DataSourceRequest request, HouseholdViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                var entity = _mapper.Map<Household>(model);
                entity = _service.Add(entity);
                model = _mapper.Map<HouseholdViewModel>(entity);
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Household_Update([DataSourceRequest] DataSourceRequest request, HouseholdViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                Household entity = _mapper.Map<Household>(model);
                Household existingEntity = _service.Get(model.ID);
                if (existingEntity != null)
                    entity = _service.Update(entity);
                else
                    entity = _service.Add(entity);
                model = _mapper.Map<HouseholdViewModel>(entity);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Household_Destroy([DataSourceRequest] DataSourceRequest request, HouseholdViewModel model)
        {
            if (model != null)
            {
                var entity = _service.Get(model.ID);
                if (entity != null)
                    _service.Delete(entity);
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }
        #endregion

    }
}

WillingToJoin/Areas/CRM2/Controllers/HouseholdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Kendo.Mvc.UI;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WillingToJoin.Shared.Data;
using WillingToJoin.Shared.Services.Contacts;
using Kendo.Mvc.Extensions;
using AutoMapper;
using WillingToJoin.Areas.CRM2.Models;

namespace WillingToJoin.Areas.CRM2.Controllers
{
    public class HouseholdsController : Controller
    {
        private WTJContext db = new WTJContext();
        private readonly IHouseholdService _service;
        private readonly IMapper _mapper;

        public HouseholdsController(IHouseholdService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        // GET: /CRM2/Households/
        public ActionResult Index()
        {
            //var households = db.Households.Include(h => h.HouseholdStatu).Take(10);
            //ViewBag.households = db.Households.Include(h => h.HouseholdStatu).Take(10);
            //return View(households.ToList());
            return View();
        }

        // GET: /CRM2/Households/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //PopulateHouseholdStatus();
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }

            var householdDetails = _mapper.Map<HouseholdsDetailsViewModel>(household);

            return View(householdDetails);
        }

        public void PopulateHouseholdStatus()
        {
            WTJContext context = new WTJContext();
            var statuses = context.HouseholdStatuses.ToList();
            List<SelectListItem> householdStatuses = statuses.Select(status => new SelectListItem
            {
                Value = status.HouseholdStatusID.ToString(),
                Text = status.Name
            }).ToList();

            ViewData["householdStatuses"] = householdStatuses;
        }

        public ActionResult HouseholdsDetails_Read([DataSourceRequest]DataSourceRequest request)
        {
            var entities = _service.GetAll();
            return Json(entities.ToDataSourceResult(request, s => _mapper.Map<HouseholdsDetailsViewModel>(s)));
        }

        public ActionResult Households_Read([DataSourceRequest]DataSourceRequest request)
        {
            var entities = _service.GetAll();
            return Json(entities.ToDataSourceResult(request, s => _mapper.Map<HouseholdsViewModel>(s)));
        }

        // GET: /CRM2/Households/Create
        public ActionResult Create()
        {
            ViewBag.HouseholdStatusID = new SelectList(db.HouseholdStatuses, "HouseholdStatusID", "Name");
            return View();
        }

        // POST: /CRM2/Households/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,ImportedID,OwnerID,Name,Npo02FormulaMailingAddress,Npo02HouseholdEmail,Npo02HouseholdPhone,Npo02MailingCity,Npo02MailingPostalCode,Npo02MailingState,Npo02MailingStreet,Npo02FormalGreeting,Npo02InformalGreeting,CvmReID,ExportedToCvm,Note,CvmFormalGreeting,CvmInformalGreeting,GroupSource,HouseholdStatusID")] Household household)
        {
            if (ModelState.IsValid)
            {
                db.Households.Add(household);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HouseholdStatusID = new SelectList(db.HouseholdStatuses, "HouseholdStatusID", "Name", household.HouseholdStatusID);
            return View(household);
        }

        // GET: /CRM2/Households/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseholdStatusID = new SelectList(db.HouseholdStatuses, "HouseholdStatusID", "Name", household.HouseholdStatusID);
            return View(household);
        }

        // POST: /CRM2/Households/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,ImportedID,OwnerID,Name,Npo02FormulaMailingAddress,Npo02HouseholdEmail,Npo02HouseholdPhone,Npo02MailingCity,Npo02MailingPostalCode,Npo02MailingState,Npo02MailingStreet,Npo02FormalGreeting,Npo02InformalGreeting,CvmReID,ExportedToCvm,Note,CvmFormalGreeting,CvmInformalGreeting,GroupSource,HouseholdStatusID")] Household household)
        {
            if (ModelState.IsValid)
            {
                db.Entry(household).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseholdStatusID = new SelectList(db.HouseholdStatuses, "HouseholdStatusID", "Name", household.HouseholdStatusID);
            return View(household);
        }

        // GET: /CRM2/Households/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // POST: /CRM2/Households/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Household household = db.Households.Find(id);
            db.Households.Remove(household);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WillingToJoin/Areas/CRM2/Views/Households/Create.cshtml
@model WillingToJoin.Shared.Data.Household

@{
    ViewBag.Title = "Create";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Create</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Create Household</h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ImportedID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImportedID)
                @Html.ValidationMessageFor(model => model.ImportedID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerID)
                @Html.ValidationMessageFor(model => model.OwnerID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02FormulaMailingAddress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02FormulaMailingAddress)
                @Html.ValidationMessageFor(model => model.Npo02FormulaMailingAddress)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02HouseholdEmail, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02HouseholdEmail)
                @Html.ValidationMessageFor(model => model.Npo02HouseholdEmail)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02HouseholdPhone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02HouseholdPhone)
                @Html.ValidationMessageFor(model => model.Npo02HouseholdPhone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02MailingCity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02MailingCity)
                @Html.ValidationMessageFor(model => model.Npo02MailingCity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02MailingPostalCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02MailingPostalCode)
                @Html.ValidationMessageFor(model => model.Npo02MailingPostalCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02MailingState, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02MailingState)
                @Html.ValidationMessageFor(model => model.Npo02MailingState)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02MailingStreet, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02MailingStreet)
                @Html.ValidationMessageFor(model => model.Npo02MailingStreet)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02FormalGreeting, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02FormalGreeting)
                @Html.ValidationMessageFor(model => model.Npo02FormalGreeting)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Npo02InformalGreeting, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Npo02InformalGreeting)
                @Html.ValidationMessageFor(model => model.Npo02InformalGreeting)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CvmReID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CvmReID)
                @Html.ValidationMessageFor(model => model.CvmReID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExportedToCvm, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExportedToCvm)
                @Html.ValidationMessageFor(model => model.ExportedToCvm)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note)
                @Html.ValidationMessageFor(model => model.Note)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CvmFormalGreeting, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CvmFormalGreeting)
                @Html.ValidationMessageFor(model => model.CvmFormalGreeting)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CvmInformalGreeting, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CvmInformalGreeting)
                @Html.ValidationMessageFor(model => model.CvmInformalGreeting)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupSource, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupSource)
                @Html.ValidationMessageFor(model => model.GroupSource)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdStatusID, "HouseholdStatusID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HouseholdStatusID", String.Empty)
                @Html.ValidationMessageFor(model => model.HouseholdStatusID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
				@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-white"})
            </div>
        </div>
    </div>
}

                </div>
            </div>
        </div>
    </div>
 </div>

 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WillingToJoin/Areas/CRM2/Views/Households/Delete.cshtml
@model WillingToJoin.Shared.Data.Household

@{
    ViewBag.Title = "Delete";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Delete</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Delete</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Household</h5>
                </div>
                <div class="ibox-content">
				<h4 class="text-danger">Are you sure you want to delete this?</h4>
				 <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImportedID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImportedID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02FormulaMailingAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02FormulaMailingAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02HouseholdEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02HouseholdEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02HouseholdPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02HouseholdPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02MailingCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02MailingCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02MailingPostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02MailingPostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02MailingState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02MailingState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02MailingStreet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02MailingStreet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02FormalGreeting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02FormalGreeting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Npo02InformalGreeting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Npo02InformalGreeting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CvmReID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CvmReID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExportedToCvm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExportedToCvm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CvmFormalGreeting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CvmFormalGreeting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CvmInformalGreeting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CvmInformalGreeting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupSource)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupSource)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseholdStatu.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseholdStatu.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white"})
        </div>
    }



                </div>
            </div>
        </div>
    </div>
 </div>

WillingToJoin/Areas/CRM2/Views/Households/Index.cshtml
@using WillingToJoin.Areas.CRM2.Models
@model IEnumerable<WillingToJoin.Shared.Data.Household>

@{
    ViewBag.Title = "Index";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Index</h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Household</strong>
            </li>
        </ol>
    </div>
</div>

@*Add Grid Right Here*@
@(Html.Kendo().Grid<HouseholdsViewModel>()
        .Name("grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.ID).Width(20).Title(" ").Filterable(false).ClientTemplate("<a href='" + Url.Action("Details", "Households") + "/#=ID#'>View Details</a>");
            columns.Bound(c => c.ID).Visible(false);
            columns.Bound(c => c.Name).Width(20);
            columns.Bound(c => c.Npo02MailingCity).Title("City").Width(20);
            columns.Bound(c => c.Npo02MailingState).Title("State").Width(10);
        })
        
        .Resizable(resize => resize.Columns(true))
        .Filterable(ftb => ftb.Mode(GridFilterMode.Row))
        .HtmlAttributes(new { style = "height: 550px;" })
        .Scrollable()
        //.Groupable()
        .Sortable()
        .Pageable()
        .DataSource(dataSource => dataSource
            .Ajax()
            .PageSize(15)
            .ServerOperation(true)
            .Read(read => read.Action("Households_Read", "Households"))
        )
        .Resizable(resize => resize.Columns(true))
)

<div id="grid"></div>
<script>
$("#grid").kendoGrid({
  columns: [{
    field: "name",
    headerAttributes: {
      "class": "table-header-cell",
      style: "text-align: Center; font-size: 14px"
    }
  }],
  //dataSource: [ { name: "Jane Doe" }, { name: "John Doe" } ]
});
</script>

@*<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>List of Household</h5>
                        <div class="ibox-tools">
                            @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-xs"})
                        </div>
                    </div>
                    <div class="ibox-content">

    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HouseholdStatu.Name)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HouseholdStatu.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.ID }, new { @class = "btn btn-primary btn-sm"})
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }, new { @class = "btn btn-white btn-sm"})
                @Html.ActionLink("Delete", "Delete", new { id=item.ID }, new { @class = "btn btn-white btn-sm"})
            </td>
        </tr>
    }

    </table>

                    </div>
                </div>
            </div>
        </div>
     </div>*@