WillingToJoin/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WillingToJoin.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

WillingToJoin/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WillingToJoin.Models;

namespace WillingToJoin.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }



		[HttpPost]
		public ActionResult Index(ContactViewModel contactViewModel)
		{
			if (ModelState.IsValid)
			{
				string emailFrom = ConfigurationManager.AppSettings["emailFrom"];
				string passwordFrom = ConfigurationManager.AppSettings["passwordFrom"];
				string smtpClientHost = ConfigurationManager.AppSettings["smtpClientHost"];
				string emailTo = ConfigurationManager.AppSettings["emailTo"];
				int smtpClientPort = int.Parse(ConfigurationManager.AppSettings["smtpClientPort"]);
				string type = (contactViewModel.Type == 1) ? "General" : "Prayer Team";

				MailMessage mail = new MailMessage(emailFrom, emailTo);
				mail.Subject = "Willing to Join";
				mail.Body = string.Format("Name: {0}\n\rType: {1}\n\rEmail: {2}\n\rMessage: {3}", contactViewModel.Name, type, contactViewModel.Email, contactViewModel.Message);

				SmtpClient client = new SmtpClient();
				client.Host = smtpClientHost;
				client.Port = smtpClientPort;
				client.DeliveryMethod = SmtpDeliveryMethod.Network;
				client.Credentials = new NetworkCredential(emailFrom, passwordFrom);
				client.Send(mail);
			}
			else
			{
				contactViewModel = new ContactViewModel();
			}
			return View(contactViewModel);
		}
	}
}

WillingToJoin/Controllers/FiftyFiftyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WillingToJoin.Controllers
{
    public class FiftyFiftyController : Controller
    {
        // GET: FiftyFifty
        public ActionResult Index()
        {
            return View();
        }
    }
}

WillingToJoin/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WillingToJoin.Controllers
{
    public class SupportController : Controller
    {
        // GET: Support
        public ActionResult Index()
        {
            return View();
        }
    }
}

WillingToJoin/Views/Shared/_Footer.cshtml
<footer class="colophon top" >
   
</footer>
<footer class="colophon bottom">
    <div class="x-container max width">

        <div class="social-global"><a href="https://www.facebook.com/Willing-to-Join-Wensel-Family-564339736992329/" class="facebook" title="Facebook" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></div>

        <ul id="menu-base-2" class="nav">
            <li class=""><a href="http://www.willingtojoin.org/">Home</a></li>
            <li class=""><a href="http://www.willingtojoin.org/church-planting/">Church Planting</a></li>
            <li class=""><a href="http://www.willingtojoin.org/animal-health-care/">Animal Health Care</a></li>
            <li class=""><a href="http://www.willingtojoin.org/photo-galleries/">Photo Galleries</a></li>
            <li class=""><a href="http://www.willingtojoin.org/support-us/">Support Us</a></li>
            <li class=""><a href="http://www.willingtojoin.org/50-50/">50-50</a></li>
            <li class=""><a href="http://www.willingtojoin.org/about-us/">About Us</a></li>
            <li class=""><a href="http://www.willingtojoin.org/contact-us/">Contact Us</a></li>
        </ul>
      

    </div>
</footer>

WillingToJoin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Willing to Join | @ViewBag.Title</title>
	    @Scripts.Render("~/bundles/jquery")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    
</head>
<body class="page">
   

    <div class="container">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Main view  -->
        @RenderBody()

        <!-- Footer -->
        @Html.Partial("_Footer")

    </div>
    <a class="scroll-top right fade" href="#top" title="Back to Top">
        <i class="fa fa-chevron-up"></i>
    </a>
    <script src="~/Scripts/kendo/2015.3.1111/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(window).scroll(function () {
            var h = $(window).height();
            if ($(this).scrollTop() > h) {
                $('.scroll-top').addClass('in');
            } else {
                $('.scroll-top').removeClass('in');
            }
        });
    </script>
</body>
</html>

WillingToJoin/Views/Shared/_Navigation.cshtml
<nav class="navbar navbar-default" id="top">
    <div class="container-fluid width">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="~/Content/images/logo.png" /></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Church Planting", "Index", "ChurchPlanting")</li>
                <li>@Html.ActionLink("Animal Health Care", "Index", "AnimalHealthCare")</li>
                <li>@Html.ActionLink("Photo Gallery", "Index", "PhotoGallery")</li>
                <li>@Html.ActionLink("Support Us", "Index", "Support")</li>
                <li>@Html.ActionLink("50-50", "Index", "FiftyFifty")</li>
                <li>@Html.ActionLink("About Us", "Index", "About")</li>
                <li>@Html.ActionLink("Contact Us", "Index", "Contact")</li>
                <li><a href="#" ><i class="fa fa-search" aria-hidden="true"></i></a></li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>